require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2
  Exclude:
    - 'release-gem'
    - 'test/**/*'
    - 'lib/tasks/**/*'

Rails:
  Enabled: true

Style:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'
