inherit_gem:
  theforeman-rubocop:
    - all.yml

AllCops:
  NewCops: disable
  Exclude:
    - 'release-gem'
    - 'test/**/*'
    - 'lib/tasks/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'templates/**/*'
    - 'vendor/**/*'

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'
